CREATE TABLE bmrs.derbmdata (
  header_record_type                    VARCHAR(255)
, header_file_type                      VARCHAR(255)
, header_settlement_date                DATE
, header_settlement_period              INT
, record_type                           VARCHAR(255)
, bm_unit_id                            VARCHAR(255)
, bm_unit_type                          VARCHAR(255)
, lead_party_name                       VARCHAR(255)
, ngc_bm_unit_name                      VARCHAR(255)
, settlement_date                       DATE
, settlement_period                     INT
, data_type                             VARCHAR(255)
, acceptance_id                         VARCHAR(255)
, short_acceptance_flag                 VARCHAR(255)
, bid_offer_pair1_accepted_volume       DECIMAL
, bid_offer_pair2_accepted_volume       DECIMAL
, bid_offer_pair3_accepted_volume       DECIMAL
, bid_offer_pair4_accepted_volume       DECIMAL
, bid_offer_pair5_accepted_volume       DECIMAL
, bid_offer_pair6_accepted_volume       DECIMAL
, bid_offer_pair_1_accepted_volume      DECIMAL
, bid_offer_pair_2_accepted_volume      DECIMAL
, bid_offer_pair_3_accepted_volume      DECIMAL
, bid_offer_pair_4_accepted_volume      DECIMAL
, bid_offer_pair_5_accepted_volume      DECIMAL
, bid_offer_pair_6_accepted_volume      DECIMAL
, bid_offer_pair1_cash_flow             DECIMAL
, bid_offer_pair2_cash_flow             DECIMAL
, bid_offer_pair3_cash_flow             DECIMAL
, bid_offer_pair4_cash_flow             DECIMAL
, bid_offer_pair5_cash_flow             DECIMAL
, bid_offer_pair6_cash_flow             DECIMAL
, bid_offer_pair_1_cash_flow            DECIMAL
, bid_offer_pair_2_cash_flow            DECIMAL
, bid_offer_pair_3_cash_flow            DECIMAL
, bid_offer_pair_4_cash_flow            DECIMAL
, bid_offer_pair_5_cash_flow            DECIMAL
, bid_offer_pair_6_cash_flow            DECIMAL
, total                                 DECIMAL
, active_flag                           VARCHAR(255)
);
