CREATE TABLE bmrs.detsysprices(
     header_record_type                 VARCHAR(255),
     header_file_type                   VARCHAR(255),
     record_type                        VARCHAR(255),
     settlement_date                    DATE,
     settlement_period                  INT,
     settlement_period_time             TIME WITHOUT TIME ZONE,
     data_index                         INT,
     id                                 VARCHAR(255),
     acceptance_id                      VARCHAR(255),
     bid_offer_pair_id                  VARCHAR(255),
     cadl_flag                          VARCHAR(255),
     so_flag                            VARCHAR(255),
     stor_flag                          VARCHAR(255),
     repriced_indicator                 VARCHAR(255),
     reserve_scarcity_price             DECIMAL,
     bid_offer_price                    DECIMAL,
     bid_offer_volume                   DECIMAL,
     dmat_adjusted_volume               DECIMAL,
     arbitrage_adjusted_volume          DECIMAL,
     niv_adjusted_volume                DECIMAL,
     par_adjusted_volume                DECIMAL,
     final_price                        DECIMAL,
     transmission_loss_multiplier       DECIMAL,
     tlm_adjusted_volume                DECIMAL,
     tlm_adjusted_cost                  DECIMAL,
     tlm_adjusted_volume_total          DECIMAL,
     tlm_adjusted_cost_total            DECIMAL
);